manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/Easontons
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: other-sup
      import: app/west.yml
  self:
    path: config
