manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/Easontons
  projects:
    - name: zmk
      remote: Easontons
      revision: main
      import: app/west.yml
  self:
    path: config
